### ISSUE TITLE
Linux VM scale set encryption at host disabled

### ISSUE THREAD

**Issue by tlchaffi** [amestofortytwo/terraform-azurerm-selfhostedrunnervmss#49]
Attempted to use the Terraform module to deploy a Linux VMSS. Snyk IaC scanned the Terraform plan output, and found a Medium issue we'd like resolved.

Terraform used:

> module "vmss" {
  source                                             = "amestofortytwo/selfhostedrunnervmss/azurerm"
  operating_system                          = "ubuntu"
  runner_platform                             = "github"
  username                                        = "runneradmin"
  resource_group_name                   = azurerm_resource_group.example.name
  use_existing_resource_group       = true
  location                                            = local.primary_region
  virtual_machine_scale_set_name = local.vmss_username
  sku                                                    = "D2s_v3" # General Purpose, 2 vCPU, 8 GiB RAM, 16 GiB Temporary Storage
  subnet_id                                         = data.azurerm_subnet.example.id
  use_custom_subnet                        = true
  tags                                                   = var.tags
}

Snyk output:
>Issues
Medium Severity Issues: 1
  [Medium] Linux VM scale set encryption at host disabled
  Info:    Linux VM scale set encryption at host disabled. Storage devices
           attached to the VM will not be encrypted at rest
  Rule:    https://security.snyk.io/rules/cloud/SNYK-CC-AZURE-475
  Path:    resource >
           azurerm_linux_virtual_machine_scale_set[self_hosted_runners["0"]] >
           encryption_at_host_enabled
  File:    plan.json
  Resolve: Set `encryption_at_host_enabled` attribute to `true`

As a workaround, I'll probably skip the module, and copy some of the module code to implement these VMSS.

**Comment by tlchaffi** [comment]
@mysteq or @mariussm could we adjust the module to support encryption at rest?

**Comment by tlchaffi** [comment]
Thank you!

**Comment by mariussm** [comment]
No problem @tlchaffi, thanks for reporting :)
