### ISSUE TITLE
Configure VMSS Self-Hosted Agents as Ephemeral 

### ISSUE THREAD

**Issue by tlchaffi** [amestofortytwo/terraform-azurerm-selfhostedrunnervmss#58]
@mysteq and team, we really appreciate how much you've been helping us out. I feel like I keep pestering you guys, but we are finding a lot of success using your images straight from the Azure Marketplace. We appreciate that.

One item we've discovered is by using the image, and applying it to a VMSS that autoscales (up and down), we end up with a lot of `offline` runners in our GitHub org settings panel. Per [GitHub's documentation](https://github.blog/changelog/2022-08-03-github-actions-remove-offline-self-hosted-runners/) I believe these will fall off in 14 days. But, in a few days worth of scaling up and down, we've generated 16 pages of self-hosted runners that are `offline`.

Is there a possibility, that we could add the `--ephemeral` flag, within the `create-latest-svc.sh` script? I'd imagine a tweak somewhere between lines 181 and 184 would do the trick?

This should drop any `offline` runner, thats been `offline` for a day, keeping that list manageable.

**Comment by mysteq** [comment]
Ephemeral is on our todo-list also, just need a little time to figure out the best way to do it and implement it. Will update as soon as we have something for it :)

**Comment by tlchaffi** [comment]
Just checking in and poking the issue, to ensure its not auto-closed.

**Comment by mysteq** [comment]
We've done a bit of rework of the script, and with this we've added support for an ephemeral parameter. However that would mean the runner only runs one workflow, and then exist, and the VM instance would require to be redeployed. We're currently testing some code for it to see how it could work.

However we're also testing code that would remove the runner, when the instance get's terminated, that is dependant on termination notification on the VMSS. I would believe this would better suit your needs (if it works out like we want :) )

These changes are currently just in:
https://github.com/amestofortytwo/terraform-azurerm-selfhostedrunnervmss/blob/main/scripts/script_preview_v2.sh

We'll test that it works as it should, and then move functionality over to the other, and add some documentation.

**Comment by tlchaffi** [comment]
This makes sense. As I think about it, I believe the ephemeral flag was originally added for GitHub, as some deployments of GH runners are really "jobs" in a kubernetes cluster. So, a Job would start up, complete the compute for the GH action, and then clean up.

The idea of doing a removal step when a vmss member is deallocated or scaled down really does make sense.

**Comment by mysteq** [comment]
Script has been updated. 
I've added some doc for it here, and it should basically be to just enable termination notification on the VMSS with a timeout.
https://docs.byfortytwo.com/Self%20Hosted%20Runners/GitHub/step2/#offboard-github-runner-upon-termination-eventsscale-down

Currently running with this ourselves, so it should work fine.

**Comment by mysteq** [comment]
Going to close this for now then, as both a way for the agent to do removal when an instance is scaled down (would be the recommended way), and ephemeral (with parameter "-e" in the script), has been implemented.
